app_main/urls.py
from django.urls import path
from app_main.views import *

app_name = "app_main"


urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/", ProductView.as_view(), name="product"),
    path("contact/", ContactView.as_view(), name="contact"),
]

gemotex/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = "app_main.views.custom_page_not_found_view"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("app_main.urls", "app_main")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
{% load static %}
<footer class="footer-bg flex w-full flex-col items-center justify-center bg-zinc-900 text-white">
  <div class="container">
    <div class="mt-8 grid grid-cols-1 items-center gap-8 md:mt-16 md:grid-cols-2 md:gap-4 xl:grid-cols-4">
      <a class="font-perker text-3xl md:text-4xl" href="/">Gemotex</a>

      <!-- item-1 -->
      <div class="flex items-center gap-8">
        <img loading="lazy" src="{% static 'images/box-white.png' %}" class="w-10 md:w-14 aspect-square" alt="" />
        <h5 class="font-semibold uppercase">
          FREE SHIPPING & RETURN POLICY
        </h5>
      </div>

      <!-- item-2 -->
      <div class="flex items-center gap-8">
        <img loading="lazy" src="{% static 'images/headphone-white.png' %}" alt="" class="w-10 md:w-14 aspect-square" />
        <h5 class="font-semibold uppercase">90-DAY WARRANTY</h5>
      </div>

      <!-- item-3 -->
      <div class="flex items-center gap-8">
        <img loading="lazy" src="{% static 'images/history-white.png' %}" class="w-10 md:w-14 aspect-square" alt="" />
        <h5 class="font-semibold uppercase">
          NEW PRODUCT OFFERINGS & DEALS
        </h5>
      </div>
    </div>

    <div class="my-8 h-px bg-zinc-700"></div>

    <div class="mb-8 grid w-full gap-16 md:mb-16 lg:grid-cols-9 lg:gap-0">
      {% if footer %}
      <div class="flex flex-col items-center md:items-start lg:col-span-4">
        <p
          class="mb-5 max-w-md text-center text-sm leading-relaxed text-white md:max-w-none md:text-left lg:text-justify">
          {{ footer.details }}
        </p>
        <ul class="flex gap-5 text-xl">
          <li>
            <a href="{% if  footer.facebook_link %}{{ footer.facebook_link }}{% else %}#{% endif %}"
              class="grid aspect-square w-8 place-items-center rounded-full bg-white text-zinc-500">
              <i class="ti ti-brand-facebook"></i>
            </a>
          </li>
          <li>
            <a href="{% if  footer.linkedin_link %}{{ footer.linkedin_link }}{% else %}#{% endif %}"
              class="grid aspect-square w-8 place-items-center rounded-full bg-white text-zinc-500">
              <i class="ti ti-brand-linkedin"></i>
            </a>
          </li>
          <li>
            <a href="{% if  footer.twitter_link %}{{ footer.twitter_link }}{% else %}#{% endif %}"
              class="grid aspect-square w-8 place-items-center rounded-full bg-white text-zinc-500">
              <i class="ti ti-brand-twitter"></i>
            </a>
          </li>
          <li>
            <a href="{% if  footer.youtube_link %}{{ footer.youtube_link }}{% else %}#{% endif %}"
              class="grid aspect-square w-8 place-items-center rounded-full bg-white text-zinc-500">
              <i class="ti ti-brand-youtube"></i>
            </a>
          </li>
        </ul>
      </div>
      {% endif %}

      <div class="flex w-full flex-col md:flex-row justify-center gap-10 lg:col-span-5 lg:pl-10 xl:pl-16">
        <div class="flex-1 w-full">
          <h2 class="mb-3 text-sm font-bold md:text-base">Quick Links</h2>
          <div class="flex text-[0.8rem] gap-6 md:text-sm">
            <div class="flex flex-col gap-3">
              <a href="{% url 'app_main:about' %}">About Us</a>
              <a href="{% url 'app_main:contact' %}">Contact Us</a>
              <a href="{% url 'app_main:about' %}">Privacy Policy</a>
            </div>
            <div class="flex flex-col gap-3">
              <a href="{% url 'app_main:about' %}">Support Policy</a>
              <a href="{% url 'app_main:about' %}">Our Services</a>
              <a href="{% url 'app_main:product_list' %}">Products</a>
            </div>
          </div>
        </div>

        <div class="w-full md:flex-1">
          <h2 class="mb-3 text-sm font-bold md:text-base">Contact Us</h2>
          {% if contact %}
          <div class="flex flex-col gap-3 text-[0.8rem] md:text-sm">
            <a href="#" class="flex items-center gap-4">
              <i class="ti ti-map-pin-filled text-[1.25em]"></i>
              <span>{{ contact.address }}</span>
            </a>
            <a href="#" class="flex items-center gap-4">
              <i class="ti ti-phone-call text-[1.25em]"></i>
              <span>{{ contact.phone }}</span>
            </a>
            <a href="#" class="flex items-center gap-4">
              <i class="ti ti-mail-filled text-[1.25em]"></i>
              <span>{{ contact.email }}</span>
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4 w-full bg-zinc-800 p-4 text-center text-xs sm:text-sm">
    <p class="text-white">Developed by <a class="text-green-500 hover:underline" href="https://www.itsourcebd.com/"
        target="_blank">ITSOURCE</a> | © <script>document.write(new Date().getFullYear());</script> gemotex. All rights reserved.</p>
  </div>
</footer>

templates/components/nav.html
<nav class="w-full bg-white sticky top-0 z-50" aria-label="Global">
  <div class="nav-wrapper container flex h-16 items-center justify-between">
    <div class="flex w-full items-center justify-between md:w-auto">
      <a class="flex-none text-3xl font-semibold font-perker" href="{% url 'app_main:home' %}">Gemotex</a>
      <div class="nav-icons flex items-center gap-4 md:hidden">
        <a href="{% url 'admin:index' %}" class="grid place-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="24" height="24"
            viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
            stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"></path>
            <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
          </svg>
        </a>
        <button
          class="nav-toggle-btn inline-flex items-center justify-center gap-2 rounded-md border bg-white p-2 align-middle text-sm text-zinc-700 shadow-sm transition-all hover:bg-zinc-50 focus:outline-none focus:ring-2 focus:ring-zinc-600 focus:ring-offset-2 focus:ring-offset-white">
          <i class="ti ti-menu-2"></i>
        </button>
      </div>
    </div>

    <div id="navbar" class="">
      <ul class="nav-menu">
        <li>
          <a class="nav-link active" href="/">Home</a>
        </li>

        <li class="dropdown [--strategy:static] md:[--strategy:absolute]">
          <button type="button" class="nav-link menu-toggle-btn flex items-center gap-x-5">
            Products
            <i class="ti ti-chevron-down"></i>
          </button>

          <ul class="dropdown-menu">
            <li><a class="menu-link" href="{% url 'app_main:product_list' %}">All Category</a></li>
            {% for category in categories %}
            <li class="submenu__left submenu [--strategy:static] md:[--strategy:absolute]">
              <button type="button" class="submenu-btn menu-toggle-btn">
                {{category.category_name}}
                <i class="ti ti-chevron-right rotate-90 md:rotate-0"></i>
              </button>
              <ul class="submenu-menu">

                <li><a class="menu-link"
                    href="{% url 'app_main:product_list' %}?category={{category.category_name}}">All Subcategory</a>
                </li>
                {% for subcategory in category.subcategories.all %}
                <li><a class="menu-link"
                    href="{% url 'app_main:product_list' %}?category={{category.category_name}}&subcategory={{subcategory.subcategory_name}}">{{subcategory.subcategory_name}}</a>
                </li>
                {% endfor %}
              </ul>
            </li>
            {% endfor %}
          </ul>
        </li>

        <li class="">
          <a class="nav-link" href="{% url 'app_main:contact' %}">Contact</a>
        </li>
        <li class="">
          <a class="nav-link" href="{% url 'app_main:about' %}">About</a>
        </li>

        <li class="mt-4 inline-block md:mt-0">
          <a href="{% url 'admin:index' %}" class="rounded flex w-max items-center gap-2 uppercase bg-zinc-800 px-2 py-2 text-sm text-white">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="16" height="16"
              viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
              stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"></path>
              <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
            </svg>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/product-card.html
<a href="{% url 'app_main:product' product.id %}"
    class="product-card relative border-2 bg-white p-6 transition-all duration-300 hover:border-zinc-700">
    <div class="wrapper">
        <div class="flex items-center justify-between">
            <span class="rounded-sm bg-zinc-900 px-1.5 pb-0.5 pt-1 text-xs leading-none text-white">
                {{product.tag}}
            </span>
            <span
                class="ml-auto grid aspect-square w-10 place-items-center rounded-full bg-zinc-200 transition-colors hover:bg-zinc-700 hover:text-white">
                <i class="ti ti-heart text-xl"></i>
            </span>
        </div>
        <img loading="lazy" src="{% if product.cover_image %}{{product.cover_image.url}}{% endif %}" alt=""
            class="my-3 aspect-square w-full object-cover" />
        <div class="card-infos">
            <span class="text-xs font-semibold uppercase text-zinc-600">
                {{product.subcategory.subcategory_name}}
            </span>
            <h4 class="mb-1 line-clamp-1 text-xl font-semibold uppercase text-zinc-900">
                {{product.title}}
            </h4>

            <span class="text-sm font-semibold uppercase text-zinc-600">
                {{product.category.category_name}}
            </span>
        </div>
    </div>
</a>